# Generated by Django 5.2.9 on 2025-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
            ],
        ),
    ]
